#!/usr/bin/env python3
"""Reformat ruleset_gen's output (srslist.h) into a constant-initialized array.

ruleset_gen emits:

    static const std::map<std::string, std::string> ruleSetMap {{"k","v"},...};

`static` gives the map internal linkage, so every translation unit that
includes srslist.h gets its own private copy and builds an independent
~0.5 MB heap map at startup. Across Throne that was ~40 MB of duplicated RAM
(only hidden when CMake UNITY_BUILD happened to merge the includes).

This rewrites it into a single, sorted, constant-initialized array:

    inline constexpr std::array<std::pair<std::string_view, std::string_view>, N>
        ruleSetList = {{ {"k","v"}, ... }};

`inline` => one definition program-wide; `constexpr` + string_view => it lives
in read-only data with zero heap and zero static-init, independent of
UNITY_BUILD. Entries are sorted by key (byte order) so lookups can binary-search
and the UI lists stay alphabetical (matching the old std::map iteration order).
"""
import re
import sys

# Entry shape only — independent of the wrapper text, so changes to the
# binary's std::map boilerplate don't break this. Keys/values are ASCII URLs
# and rule-set names with no embedded quotes.
ENTRY = re.compile(r'\{"([^"]*)","([^"]*)"\}')


def main() -> int:
    src = sys.argv[1] if len(sys.argv) > 1 else "srslist.h"
    dst = sys.argv[2] if len(sys.argv) > 2 else src

    with open(src, "r", encoding="utf-8") as f:
        text = f.read()

    pairs = ENTRY.findall(text)
    if not pairs:
        print(f"error: no entries found in {src}", file=sys.stderr)
        return 1

    # Dedup by key, keeping the first occurrence (std::map insert semantics),
    # then sort by key in byte order to match std::string_view comparison.
    seen: dict[str, str] = {}
    for key, value in pairs:
        seen.setdefault(key, value)
    entries = sorted(seen.items(), key=lambda kv: kv[0].encode("utf-8"))

    lines = [
        "#pragma once",
        "",
        "#include <array>",
        "#include <string_view>",
        "#include <utility>",
        "",
        "// Generated by ruleset_gen and reformatted by format_srslist.py.",
        "// Do not edit by hand. Sorted by key (byte order); one constant-",
        "// initialized copy in read-only data (no heap, no static init).",
        f"inline constexpr std::array<std::pair<std::string_view, std::string_view>, {len(entries)}>",
        "    ruleSetList = {{",
    ]
    lines += [f'    {{"{key}", "{value}"}},' for key, value in entries]
    lines += ["}};", ""]

    with open(dst, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))

    print(f"{dst}: {len(entries)} entries (from {len(pairs)} raw)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
